#ifndef PMDSKY_MOVE_EFFECTS_H
#define PMDSKY_MOVE_EFFECTS_H

#define EFFECT_INACTIVE 0
#define EFFECT_ACTIVE_FROM_STATUS 1
#define EFFECT_ACTIVE_FROM_EXCLUSIVE_ITEM 2

#endif // PMDSKY_MOVE_EFFECTS_H
