#include "dungeon_parameters_2.h"

const enum type_id WEATHER_BALL_TYPE_TABLE[8] = {
    TYPE_NORMAL, // WEATHER_CLEAR
    TYPE_FIRE,   // WEATHER_SUNNY
    TYPE_ROCK,   // WEATHER_SANDSTORM
    TYPE_NORMAL, // WEATHER_CLOUDY
    TYPE_WATER,  // WEATHER_RAIN
    TYPE_ICE,    // WEATHER_HAIL
    TYPE_NORMAL, // WEATHER_FOG
    TYPE_ICE     // WEATHER_SNOW
};
