#include "monster_parameters.h"

const s16 IQ_SKILL_RESTRICTIONS[NUM_IQ_SKILLS + 1] =
{
    9999,   // IQ_NONE
    4,      // IQ_TYPE_ADVANTAGE_MASTER
    1,      // IQ_ITEM_CATCHER
    2,      // IQ_COURSE_CHECKER
    4,      // IQ_SURE_HIT_ATTACKER
    4,      // IQ_QUICK_DODGER
    6,      // IQ_PP_CHECKER
    7,      // IQ_NONTRAITOR
    8,      // IQ_STATUS_CHECKER
    9,      // IQ_EXP_GO_GETTER
    9,      // IQ_EFFICIENCY_EXPERT
    9,      // IQ_WEAK_TYPE_PICKER
    10,     // IQ_ALL_TERRAIN_HIKER
    10,     // IQ_ABSOLUTE_MOVER
    11,     // IQ_TRAP_AVOIDER
    11,     // IQ_HOUSE_AVOIDER
    14,     // IQ_ENERGY_SAVER
    14,     // IQ_NONSLEEPER
    14,     // IQ_SELF_CURER
    16,     // IQ_TRAP_SEER
    20,     // IQ_LAVA_EVADER
    9,      // IQ_DEDICATED_TRAVELER
    17,     // IQ_ITEM_MASTER
    6,      // IQ_EXCLUSIVE_MOVE_USER
    24,     // IQ_ESCAPIST
    25,     // IQ_LOCK_PICKER
    26,     // IQ_STAIR_SENSOR
    27,     // IQ_COIN_WATCHER
    28,     // IQ_EXP_ELITE
    29,     // IQ_SHARPSHOOTER
    30,     // IQ_FAST_FRIEND
    31,     // IQ_PP_SAVER
    32,     // IQ_BODYGUARD
    33,     // IQ_CAUTIOUS_CREEPER
    34,     // IQ_AGGRESSOR
    35,     // IQ_DEFENDER
    36,     // IQ_INTIMIDATOR
    37,     // IQ_SURVIVALIST
    38,     // IQ_TRAP_BUSTER
    39,     // IQ_COUNTER_HITTER
    40,     // IQ_EXTRA_STRIKER
    41,     // IQ_HIT_AND_RUNNER
    42,     // IQ_PARRY_EXPERT
    43,     // IQ_QUICK_STRIKER
    44,     // IQ_NO_CHARGER
    45,     // IQ_WARY_FIGHTER
    46,     // IQ_GAP_PROBER
    47,     // IQ_POWER_PITCHER
    48,     // IQ_CONCENTRATOR
    49,     // IQ_COUNTER_BASHER
    50,     // IQ_CHEERLEADER
    51,     // IQ_NATURE_GIFTER
    52,     // IQ_WISE_HEALER
    53,     // IQ_QUICK_HEALER
    54,     // IQ_ACUTE_SNIFFER
    55,     // IQ_DEEP_BREATHER
    56,     // IQ_BRICK_TOUGH
    57,     // IQ_MULTITALENT
    58,     // IQ_TIME_TRIPPER
    59,     // IQ_ERRATIC_PLAYER
    60,     // IQ_PRACTICE_SWINGER
    61,     // IQ_NO_DEFEATIST
    62,     // IQ_HAGGLER
    63,     // IQ_CLUTCH_PERFORMER
    64,     // IQ_CRITICAL_DODGER
    65,     // IQ_MAP_SURVEYOR
    66,     // IQ_PIERCE_HURLER
    67,     // IQ_COLLECTOR
    68,     // IQ_TRUE_POWERIST
    0,      // IQ_NONE_2
};
