#include "tactics_data.h"

const bool8 TACTICS_FOLLOW_LEADER[NUM_TACTICS] =
{
    [TACTIC_LETS_GO_TOGETHER] = TRUE,
    [TACTIC_YOU_GO_THE_OTHER_WAY] = FALSE,
    [TACTIC_GO_AFTER_FOES] = FALSE,
    [TACTIC_AVOID_THE_FIRST_HIT] = FALSE,
    [TACTIC_ALL_FOR_ONE] = TRUE,
    [TACTIC_GROUP_SAFETY] = TRUE,
    [TACTIC_AVOID_TROUBLE] = TRUE,
    [TACTIC_BE_PATIENT] = TRUE,
    [TACTIC_KEEP_YOUR_DISTANCE] = TRUE,
    [TACTIC_WAIT_THERE] = FALSE,
    [TACTIC_GET_AWAY_FROM_HERE] = TRUE,
    [TACTIC_NONE] = FALSE
};
