#include "two_turn_moves_and_statuses.h"

const struct two_turn_move_and_status TWO_TURN_MOVES_AND_STATUSES[11] = {
    {MOVE_SOLARBEAM, STATUS_TWO_TURN_SOLARBEAM},
    {MOVE_SKY_ATTACK, STATUS_TWO_TURN_SKY_ATTACK},
    {MOVE_RAZOR_WIND, STATUS_TWO_TURN_RAZOR_WIND},
    {MOVE_FOCUS_PUNCH, STATUS_TWO_TURN_FOCUS_PUNCH},
    {MOVE_SKULL_BASH, STATUS_TWO_TURN_SKULL_BASH},
    {MOVE_FLY, STATUS_TWO_TURN_FLYING},
    {MOVE_BOUNCE, STATUS_TWO_TURN_BOUNCING},
    {MOVE_DIVE, STATUS_TWO_TURN_DIVING},
    {MOVE_DIG, STATUS_TWO_TURN_DIGGING},
    {MOVE_SHADOW_FORCE, STATUS_TWO_TURN_SHADOW_FORCE},
    {MOVE_NOTHING, STATUS_TWO_TURN_NONE}
};
